---

- name: Onboard Windows Servers to Azure Arc-enabled servers  
  hosts: sql-servers
  gather_facts: no
  vars:
    azure:
      azure_subscription: 
      service_principal_id: 'INSERT-SERVICE-PRINCIPAL-CLIENT-ID'
      service_principal_secret: 'INSERT-SERVICE-PRINCIPAL-SECRET'
      resource_group: rg-CDS-Arc-Agent
      tenant_id: 'INSERT-TENANT-ID'
      subscription_id: b7b320a5-af99-4acc-8ab4-ac03a7535f8d
      location: EastUS


  tasks:

    - name: Check if the Connected Machine Agent has already been downloaded on Windows servers
      win_stat:
        path: C:\Program Files\AzureConnectedMachineAgent
      register: azcmagent_win_downloaded
      when: ansible_os_family == 'Windows'

    - name: Download the Connected Machine Agent on Windows servers
      win_get_url:
        url: https://aka.ms/AzureConnectedMachineAgent
        dest: C:\temp\AzureConnectedMachineAgent.msi
      when: (ansible_os_family == 'Windows') and (not azcmagent_win_downloaded.stat.exists)

    - name: Install the Connected Machine Agent on Windows servers
      win_package:
       path: C:\temp\AzureConnectedMachineAgent.msi
      when: (ansible_os_family == 'Windows') and (not azcmagent_win_downloaded.stat.exists)

    - name: Check if the Connected Machine Agent has already been connected on windows
      win_command: '"C:\Program Files\AzureConnectedMachineAgent\azcmagent.exe" check -l "{{ azure.location }}"'
      register: azcmagent_win_connected
      when: ansible_os_family == 'Windows'
      ignore_errors: yes
      failed_when: (azcmagent_win_connected.rc not in [ 0, 16 ])
      changed_when: False

    - name: Connect the Connected Machine Agent on Windows servers to Azure
      win_shell: '& $env:ProgramFiles\AzureConnectedMachineAgent\azcmagent.exe connect --service-principal-id "{{ azure.service_principal_id }}" --service-principal-secret "{{ azure.service_principal_secret }}" --resource-group "{{ azure.resource_group }}" --tenant-id "{{ azure.tenant_id }}" --location "{{ azure.location }}" --subscription-id "{{ azure.subscription_id }}"'
      when: (ansible_os_family == 'Windows') and (azcmagent_win_connected.rc is defined and azcmagent_win_connected.rc != 0)
